# This file was generated by GoReleaser. DO NOT EDIT.
cask "nt" do
  name "nt"
  desc "CLI for interacting with Notion via its MCP server"
  homepage "https://github.com/Riki1312/nt-cli"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nt"

  on_macos do
    on_intel do
      url "https://github.com/Riki1312/nt-cli/releases/download/v#{version}/nt_darwin_amd64.tar.gz"
      sha256 "842f3cf47d8b3febff2a776b4b76877ff7d2952777f1bd504b454da1c5a297e0"
    end
    on_arm do
      url "https://github.com/Riki1312/nt-cli/releases/download/v#{version}/nt_darwin_arm64.tar.gz"
      sha256 "4047cffeea4adc5e35c795433f4482b749ce951b74619b4b31c5b489700439cb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Riki1312/nt-cli/releases/download/v#{version}/nt_linux_amd64.tar.gz"
      sha256 "369042bca1c4caec2fbfc244acef05b7d31dc230b5baa7f1f9905dd656567e12"
    end
    on_arm do
      url "https://github.com/Riki1312/nt-cli/releases/download/v#{version}/nt_linux_arm64.tar.gz"
      sha256 "42648dc4e3d459327c1f3f3d66b586265f4721d09bdf50c436e0578508ddf2f5"
    end
  end

  # No zap stanza required
end
