# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nt < Formula
  desc "CLI for interacting with Notion via its MCP server"
  homepage "https://github.com/Riki1312/nt-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Riki1312/nt-cli/releases/download/v0.1.0/nt_darwin_amd64.tar.gz"
      sha256 "f375a6f93c7430c929b17e16c7ce6b040dbf77c5fab3e6313f57f982a103f396"

      define_method(:install) do
        bin.install "nt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Riki1312/nt-cli/releases/download/v0.1.0/nt_darwin_arm64.tar.gz"
      sha256 "29e1dbefe7bf7b9f0d8d1a3c003e2c74cbdf79bfcbcae63734635c4b6cc6a424"

      define_method(:install) do
        bin.install "nt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Riki1312/nt-cli/releases/download/v0.1.0/nt_linux_amd64.tar.gz"
      sha256 "069ab60b1f12e8eec6ddf6cfe62f7014dbf9a5f5f8fbe00d5d9d7ba11cec069b"
      define_method(:install) do
        bin.install "nt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Riki1312/nt-cli/releases/download/v0.1.0/nt_linux_arm64.tar.gz"
      sha256 "2a6153f3ad7d11e617da7dab11fe07774caf9497a8900d628175d10170d254fe"
      define_method(:install) do
        bin.install "nt"
      end
    end
  end

  test do
    assert_match "nt", shell_output("#{bin}/nt --help")
  end
end
