# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nt < Formula
  desc "CLI for interacting with Notion via its MCP server"
  homepage "https://github.com/Riki1312/nt-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Riki1312/nt-cli/releases/download/v0.2.0/nt_darwin_amd64.tar.gz"
      sha256 "6b73b69710aedd277dc980076f81372b97af2389e0999aed908dda7e499368ff"

      define_method(:install) do
        bin.install "nt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Riki1312/nt-cli/releases/download/v0.2.0/nt_darwin_arm64.tar.gz"
      sha256 "b33f05de3777dc9aba91f104a301730d2f1443b2d696385c7d27b71aa0ed084b"

      define_method(:install) do
        bin.install "nt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Riki1312/nt-cli/releases/download/v0.2.0/nt_linux_amd64.tar.gz"
      sha256 "8a99238f33df80bf72f1c41fd9b268938b5595a2f54eda9cecafefe1bc9e9e0b"
      define_method(:install) do
        bin.install "nt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Riki1312/nt-cli/releases/download/v0.2.0/nt_linux_arm64.tar.gz"
      sha256 "90e474337e80253d674ff8c4dab41591b3d18b041655c09834999106659ee557"
      define_method(:install) do
        bin.install "nt"
      end
    end
  end

  test do
    assert_match "nt", shell_output("#{bin}/nt --help")
  end
end
