# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nt < Formula
  desc "CLI for interacting with Notion via its MCP server"
  homepage "https://github.com/Riki1312/nt-cli"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Riki1312/nt-cli/releases/download/v0.2.1/nt_darwin_amd64.tar.gz"
      sha256 "a842a6f4b3f666074798373f64856dfda7c0934f39f160caf2bb9ffeda1ac6b2"

      define_method(:install) do
        bin.install "nt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Riki1312/nt-cli/releases/download/v0.2.1/nt_darwin_arm64.tar.gz"
      sha256 "e4fd5b487677ee7d638dbc53ddf31fbcb8cb2854f55f27c8e98915418cea34ea"

      define_method(:install) do
        bin.install "nt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Riki1312/nt-cli/releases/download/v0.2.1/nt_linux_amd64.tar.gz"
      sha256 "e21097ba2c537a487f867a569cc00cc43c34c722b824f3cadfc46c11020c2ce7"
      define_method(:install) do
        bin.install "nt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Riki1312/nt-cli/releases/download/v0.2.1/nt_linux_arm64.tar.gz"
      sha256 "b4bf183ab7ebd899be75b91690b8f24c5959fd63534fb92bf39ad97bf93329b0"
      define_method(:install) do
        bin.install "nt"
      end
    end
  end

  test do
    assert_match "nt", shell_output("#{bin}/nt --help")
  end
end
